### ISSUE TITLE
apply will panic if the second argument is not a list

### ISSUE THREAD

**Issue by CurryPseudo** [Danielmelody/Ruschm#71]
```scheme
(apply + 1 2)
```
will
```bash
thread 'main' panicked at 'internal error: entered unreachable code', src\interpreter\library\native\base.rs:21:18
```

**Comment by Danielmelody** [comment]
You should not call it with non list, from the r7rs. 

> The apply procedure calls proc with the elements of the list
(append (list arg1 : : : ) args) as the actual arguments

Although it should not panic.
