### ISSUE TITLE
REPL loses newlines

### ISSUE THREAD

**Issue by tmtvl** [Danielmelody/Ruschm#97]
When running in REPL mode the input string gets added without newlines, which means that once a comment is added, all input afterwards will be considered part of the input.

For example:
```Scheme
(+ 2 ;3 )
   4)
```

Will be parsed as:
```Scheme
(+ 2 ;3 )   4)
```

We could solve this by one of the following ways:
1. Switch to using an input reader that doesn't strip newlines (native Rust I/O, for example).
2. Explicitly add a newline at the end of input if it isn't closed.
3. Ignore parentheses and comments in the reader and leverage the parser to see whether we need to read more at the end of an expression.

Until the entire I/O mechanism gets implemented and we can build it higher-level I would recommend just going with 2 for now, as it would require the smallest change to get it working.

**Comment by Danielmelody** [comment]
You actually mentioned 2 orthogonal problems:
1. Rustyline eats linebreaks after hitting `enter`
2. Current parser is not providing parsing state for repl
For problem 1, We use rustyline as it provide some basic features for a repl, for example backward moving cursors, history, etc. rustyline is a good start point as a repl. So your PR is a good solution for it.
For problem 2, we can solve it with the 3rd way as you list, You are welcome to send some further PRs.
